using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Anim : MonoBehaviour {

	//Use Animator parameter and empty anim (generated by the animator) or a blend tree set as main anim
	//Must write the proper name of the wanted animation in the inspector
	Animator anim;
	public string animName;

	void Start () {
		anim = GetComponentInChildren<Animator> ();
	}

	/*
	void Update () {
		if (Input.anyKey) {
			anim.Play (animName);
		} 
	}*/

	void OnCollisionEnter2D (Collision2D other){
		anim.Play(animName);
	}
}
